name: Pull-request CI/CD

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/local-action
        with:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
          FIREBASE_DISTRIBUTION_KEY: ${{ secrets.FIREBASE_DISTRIBUTION_KEY }}

      - name: Build with Gradle
        run: ./gradlew build

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the project
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/local-action
        with:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
          FIREBASE_DISTRIBUTION_KEY: ${{ secrets.FIREBASE_DISTRIBUTION_KEY }}

      - name: Run Lint
        run: ./gradlew lint

  unit-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the project
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/local-action

      - name: Run Unit Tests
        run: ./gradlew test

  instrumented-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the project
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/local-action

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Run Instrumented Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

  distribute:
    runs-on: ubuntu-latest
    needs: [ build, unit-tests, lint, instrumented-tests ]
    steps:
      - name: Checkout the project
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/local-action

      - name: Upload Internal build to Firebase
        run: ./gradlew assembleInternal appDistributionUploadInternal
