name: Pull-request CI/CD

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/local-action

      - name: Build with Gradle
        run: ./gradlew build

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the project
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-action

      - name: Run Lint
        run: ./gradlew lint

  unit-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Environment
        uses: ./.github/actions/setup-action

      - name: Run Unit Tests
        run: ./gradlew test

  instrumented-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Environment
        uses: ./.github/actions/setup-action

      - name: Run Instrumented Tests
        run: ./gradlew connectedAndroidTest

  distribute:
    runs-on: ubuntu-latest
    needs: [ build, unit-tests, lint, instrumented-tests ]
    steps:
      - name: Setup Environment
        uses: ./.github/actions/setup-action

      - name: Upload Internal build to Firebase
        run: ./gradlew assembleInternal appDistributionUploadInternal
