name: Pull-request CI/CD

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Load Google Service file
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA | base64 -di > app/google-services.json

      - name: Load Firebase Distribution Key file
        env:
          DATA: ${{ secrets.FIREBASE_DISTRIBUTION_KEY }}
        run: echo $DATA | base64 -di > firebase-distribution-key.json

      - name: Build with Gradle
        run: ./gradlew build

unit-tests:
  runs-on: ubuntu-latest
  needs: build
  steps:
      - name: Run Unit Tests
        run: ./gradlew test

instrumented-tests:
  runs-on: ubuntu-latest
  needs: build
  steps:
    - name: Run Instrumented Tests
      run: ./gradlew connectedAndroidTest

distribute:
  runs-on: ubuntu-latest
  needs: [ build, unit-tests, lint, instrumented-tests ]
  steps:
      - name: Upload Internal build to Firebase
        run: ./gradlew assembleInternal appDistributionUploadInternal
