name: Pull-request CI/CD

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Load Google Service file
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA | base64 -di > app/google-services.json

      - name: Load Firebase Distribution Key file
        env:
          DATA: ${{ secrets.FIREBASE_DISTRIBUTION_KEY }}
        run: echo $DATA | base64 -di > firebase-distribution-key.json

      - name: Build with Gradle
        run: ./gradlew build

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the project
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Load Google Service file
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA | base64 -di > app/google-services.json

      - name: Load Firebase Distribution Key file
        env:
          DATA: ${{ secrets.FIREBASE_DISTRIBUTION_KEY }}
        run: echo $DATA | base64 -di > firebase-distribution-key.json

      - name: Run Lint
        run: ./gradlew lint

  unit-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the project
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Load Google Service file
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA | base64 -di > app/google-services.json

      - name: Load Firebase Distribution Key file
        env:
          DATA: ${{ secrets.FIREBASE_DISTRIBUTION_KEY }}
        run: echo $DATA | base64 -di > firebase-distribution-key.json

      - name: Run Unit Tests
        run: ./gradlew test

  instrumented-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the project
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Load Google Service file
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA | base64 -di > app/google-services.json

      - name: Load Firebase Distribution Key file
        env:
          DATA: ${{ secrets.FIREBASE_DISTRIBUTION_KEY }}
        run: echo $DATA | base64 -di > firebase-distribution-key.json

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Run Instrumented Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          script: ./gradlew connectedCheck

  distribute:
    runs-on: ubuntu-latest
    needs: [ build, unit-tests, lint, instrumented-tests ]
    steps:
      - name: Checkout the project
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Load Google Service file
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA | base64 -di > app/google-services.json

      - name: Load Firebase Distribution Key file
        env:
          DATA: ${{ secrets.FIREBASE_DISTRIBUTION_KEY }}
        run: echo $DATA | base64 -di > firebase-distribution-key.json

      - name: Upload Internal build to Firebase
        run: ./gradlew assembleInternal appDistributionUploadInternal
